title: OpenDirectory
description: also known as OpenAppDirectory
theme: just-the-docs

url: https://openappdirectory.github.io

aux_links:
Repository: https://github.com/openappdirectory/openappdirectory.github.io
